language: python
python: 3.8
dist: xenial
env:
  global:
    - DRF="djangorestframework==3.11.0"
    - DJANGO="django==3.0.2"
matrix:
  include:
    - name: "Defaults (Python 3.8, Django 3.0, DRF 3.11)"
    - name: "Python 3.7"
      python: "3.7"
    - name: "Python 3.6"
      python: "3.6"
    - name: "Django 2.2"
      env:
        - DJANGO="django==2.2.9"
    - name: "Django 1.11"
      env:
        - DJANGO="django==1.11.27"
    - name: "Python 3.5, Django 2.2"
      python: "3.5"
      env:
        - DJANGO="django==2.2.9"
    - name: "Python 3.4, Django 2.0, DRF 3.9"
      python: "3.4"
      env:
        - DJANGO="django==2.0.13"
        - DRF="djangorestframework==3.9.4"
    - name: "Python 2.7, Django 1.8, DRF 3.6"
      python: "2.7"
      env:
        - DJANGO="django==1.8.19"
        - DRF="djangorestframework==3.6.4"

install:pip install -r requirements.txt

script: python runtests.py

