language: python
python: 3.8
dist: xenial
env:
  global:
    - DRF="djangorestframework==3.12.4"
    - DJANGO="django==3.2.4"
matrix:
  include:
    - name: "Python 3.7"
      python: "3.7"
    - name: "Python 3.6"
      python: "3.6"
    - name: "Django 2.2"
      env:
        - DJANGO="django==2.2.9"
    - name: "Django 1.11"
      env:
        - DJANGO="django==1.11.27"

install: pip install -r requirements.txt

script: python runtests.py
